name: Build And Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Run:
    runs-on: ubuntu-latest
    environment: production
    permissions: write-all

    steps:
      - name: Iterative Setup
        uses: iterative/setup-cml@v1
      - name: Checkout Self
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Pip Packages
        env:
          Git_Token: ${{secrets.GIT_TOKEN}}
        run: |
          pip install -r requirements.txt
          python3 train_model.py
          python3 test.py

          echo "# Sanity Checks" > report2.md
          cat test.txt >> report2.md
          
          echo "# RF and LR Model Score" > report.md
          cat scores.txt >> report.md
          
          echo "# Confusion Matrix & Feature Importance" > report1.md
          echo '![](./ConfusionMatrix.png "ConfusionMatrix")' >> report1.md
          echo '![](./FeatureImportance.png "FeatureImportace")' >> report1.md
          
          cat report2.md report.md report1.md > combined_file.md
          cml comment create combined_file.md
          
